services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
